spring.application.name=appointment-service


# URL del servicio de disponibilidad de veterinarios (mock-service)
vet.availability.service.url=http://localhost:8081

# JWT Configuration
jwt.secret=myVerySecretKeyForJWTTokenGenerationThatMustBeAtLeast256BitsLong123456789
jwt.expiration=86400000
